myproject/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
    path('test/', views.test, name='test'),
    path('', Dashboard.as_view(), name='Dashboard'),
    path('DashboardFilter/', DashboardFilter.as_view(), name='DashboardFilter'),

    path('Department_Setup/', Department_Setup.as_view(), name='Department_Setup'),
    path('Position_Setup/', Position_Setup.as_view(), name='Position_Setup'),
    path('Region_Setup/', Region_Setup.as_view(), name='Region_Setup'),
    path('Township_Setup/', Township_Setup.as_view(), name='Township_Setup'),
    path('Employee_List/', Employee_List.as_view(), name='Employee_List'),
    path('EmployeeCreate/', EmployeeCreate.as_view(), name='EmployeeCreate'),

    path('EmpCreate/', EmpCreate.as_view(), name='EmpCreate'),
    path('EmployeeDetailView/<int:pk>/', EmployeeDetailView.as_view(), name='EmployeeDetailView'),
    path('EmployeeAtt/', EmployeeAtt.as_view(), name='EmployeeAtt'),
    path('AttCheckout/', AttCheckout.as_view(), name='AttCheckout'),
    path('DailyAttReport/', DailyAttReport.as_view(), name='DailyAttReport'),

    path('Department_list/', Department_list.as_view(), name='Department_list'),
    path('Employee_List_Filter_byLine/<int:id>/', Employee_List_Filter_byLine.as_view(), name='Employee_List_Filter_byLine'),
    path('DailyAttendanceByLine/', DailyAttendanceByLine.as_view(), name='DailyAttendanceByLine'),
    path('TodayEmpAttendanceList/<int:id>/', TodayEmpAttendanceList.as_view(), name='TodayEmpAttendanceList'),
    path('MonthlyAttendanceByLine/<int:id>/', MonthlyAttendanceByLine.as_view(), name='MonthlyAttendanceByLine'),
    path('ComfirmAbsent/', ComfirmAbsent.as_view(), name='ComfirmAbsent'),
    path('getAbsent/<int:id>/', getAbsent.as_view(), name='getAbsent'),

    path('EmployeeGatepass/', EmployeeGatepass.as_view(), name='EmployeeGatepass'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('mr/', include('merchant.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class department(models.Model):
    department_name = models.CharField(max_length=225)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.department_name
    
class position(models.Model):
    position = models.CharField(max_length=225)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.position


class marital(models.Model):
    status = models.CharField(max_length=225)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status


class gender(models.Model):
    gender = models.CharField(max_length=225)

    def __str__(self):
        return self.gender
    
class type(models.Model):
    status = models.CharField(max_length=20)

    def __str__(self):
        return self.status
    
class edu_grade(models.Model):
    grade = models.CharField(max_length=225)

    def __str__(self):
        return self.grade

class state_region(models.Model):
    state_name = models.CharField(max_length=225)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.state_name
    
class township(models.Model):
    township = models.CharField(max_length=225)
    state = models.CharField(max_length=225)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.township


class employee_profile(models.Model):
    employee_id = models.CharField(max_length=225, unique=True)
    contract_id = models.CharField(max_length=225,blank=True, null=True)
    finger_id = models.CharField(max_length=225,blank=True, null=True)
    employee_name = models.CharField(max_length=225, blank=True, null=True)
    ssb_id = models.CharField(max_length=225, blank=True, null=True)
    nrc_no = models.CharField(max_length=225, unique=True)
    fathername = models.CharField(max_length=225)
    mothername = models.CharField(max_length=225)
    gender = models.ForeignKey(gender, on_delete=models.CASCADE)
    race = models.CharField(max_length=225, blank=True, null=True)
    religion = models.CharField(max_length=225, blank=True, null=True)
    dob = models.DateField()
    marital = models.ForeignKey(marital, on_delete=models.CASCADE, blank=True, null=True)
    entrydate = models.DateField()
    department = models.ForeignKey(department, on_delete=models.CASCADE)
    position = models.ForeignKey(position, on_delete=models.CASCADE)
    type = models.ForeignKey(type, on_delete=models.CASCADE, blank=True, null=True)
    education = models.ForeignKey(edu_grade, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=225, blank=True, null=True)
    address = models.TextField() 
    township = models.ForeignKey(township, on_delete=models.CASCADE, blank=True, null=True)
    district = models.CharField(max_length=225, blank=True, null=True)
    state_region = models.ForeignKey(state_region, on_delete=models.CASCADE, blank=True, null=True)
    resign = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='', blank=True, null=True)
    familytable = models.ImageField(upload_to='', blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.employee_name


class education_profile(models.Model):
    employee_name = models.ForeignKey(employee_profile, on_delete=models.CASCADE)
    school = models.CharField(max_length=225)
    education_level = models.CharField(max_length=225)
    from_date = models.DateField()
    to_date = models.DateField()


class work_exp(models.Model):
    employee_name = models.ForeignKey(employee_profile, on_delete=models.CASCADE)
    company = models.CharField(max_length=225)
    position = models.CharField(max_length=225)
    from_date = models.DateField()
    to_date = models.DateField()

class employee_attendance(models.Model):
    employee = models.ForeignKey(employee_profile, on_delete=models.CASCADE)
    entry_time = models.DateTimeField()
    checkout_time = models.DateTimeField(blank=True, null=True)
    att_hr = models.FloatField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.employee.employee_name

class emp_gatepass(models.Model):
    employee_name = models.CharField(max_length=255)
    emp_code = models.CharField(max_length=255)
    department = models.CharField(max_length=255)
    reason = models.CharField(max_length=255)
    departure = models.DateTimeField(blank=True, null=True)
    arrival_time = models.DateTimeField(blank=True, null=True)
    approved_by = models.CharField(max_length=255)
    status = models.PositiveIntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.employee_name


class daily_attendance_report(models.Model):
    employee = models.ForeignKey(employee_profile, on_delete=models.CASCADE)
    department = models.ForeignKey(department, on_delete=models.CASCADE, blank=True, null=True)
    attendance_day = models.PositiveIntegerField(default=1)
    ot_hour = models.FloatField(default=0.0, blank=True, null=True)
    absent = models.BooleanField(default=False)
    date = models.DateField()
    weekno = models.PositiveIntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

myproject/templates/DailyAttReport.html
{% extends 'base.html' %}

{% block content %}


<!--=============================================================-->
<div class="card-box mb-30">
						<div class="pd-20">
							<h4 class="text-blue h4 text-center"><u>Item's Data Table</u></h4>

						</div>
						<div class="pb-20">
							<table class="data-table table stripe hover nowrap">
								<thead>
									<tr>
										<th class="table-plus datatable-nosort">Item Name</th>
                                        <th>Sale Price</th>
                                        <th>Purchase Price</th>
										<th>Total Sale</th>
										<th>Sale Qty</th>
										<th>Balance Qty</th>
                                        <th>GP</th>
									</tr>
								</thead>
								<tbody>
                                {% for i in c_product %}
									<tr>
										<td class="table-plus">{{i.product__item_name}}</td>
                                        <td>{{i.product__sell_price}}</td>
                                        <td>{{i.product__pruchase_price}}</td>
										<td>{{i.sum}}</td>
                                        <td>{{i.quantity}}</td>
										<td>{{i.product__balance_qty}}</td>
                                        <td>{{i.pur}}</td>

									</tr>
                                {% endfor %}

								</tbody>
                                <tfoot>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>Total Sale Amount</td>
                                    <td>{{sale_total}}</td>
                                    <td>{{total_sale_qty}}</td>
                                    <td>Total GP</td>
                                    <td>{{gp_total.gp}}</td>

                                </tr>
                                </tfoot>
							</table>
						</div>
					</div>

<div class="row">


</div>




{% endblock content %}

myproject/templates/Employee_List_Filter_byLine.html
{% extends 'base.html' %}

{% block content %}

<div class="card-box mb-30">
	
    <div class="pd-20 m-2">
        <h5>Employee_list</h5><hr>
       
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-info">

                <th>no</th>
                <th>Name</th>
                <th>Code</th>
                <th>SSB</th>
                <th>Role</th>
                <th>Report</th>



            </tr>
            </thead>
            <tbody id="emplist">
            {% for p in emp %}
            <tr class="emptr">
                <td class="emppid">{{p.id}}</td>
                <td><b>{{p.employee_name}}</b></td>
                <td><b>{{p.employee_id}}</b></td>
                <td>{{p.ssb_id}}</td>
                <td>{{p.position}}</td>
                <td><a href="#" class="btn btn-sm btn-secondary">report</a></td>
                
            </tr>
            {% endfor %}

            </tbody>
        </table>


    </div>
    
</div>
{% load static %}
<script src="{% static 'jquery/jquery-3.2.1.slim.min.js' %}"></script>




{% endblock content %}

myproject/templates/MonthlyAttendanceByLine.html
{% extends 'base.html' %}

{% block content %}


<div class="card-box mb-30">
	
    <div class="pd-20 m-1">
        
        <a href="#" class="h4"> [ {{dept_obj}} ] </a>|
        <button type="button" class="btn btn-sm" data-bgcolor="#00b489" data-color="#ffffff" data-toggle="modal" data-target="#datefilter-modal">
             Filter <i class="fa fa-calendar" aria-hidden="true"></i>
        </button>
        <div class="modal fade" id="datefilter-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myLargeModalLabel">Filter</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <form action="{% url 'myapp:MonthlyAttendanceByLine' dept_obj.id %}" method="post">{% csrf_token %}
                    <div class="modal-body">
                        
                        <div class="row">
                            <div class="col-6">
                                <label for="startdate">Start Date</label>
                                <input type="date" name="startdate" id="" class="form-control">
                            </div>
                            <div class="col-6">
                                <label for="enddate">End Date</label>
                                <input type="date" name="enddate" id="" class="form-control">
                            </div>
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn" data-bgcolor="#00b489" data-color="#ffffff">Filter <i class="fa fa-calendar" aria-hidden="true"></i></button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        <hr>
       
        <table class="table table-responsive">
            
            {% for employee in emp %}
            <tbody>
            
            <tr>
                <td>{{employee.employee_name}}</td>
                
                {% for entry in employee.daily_attendance_report_set.all %}

                {% if entry.date < first_date %}
                {% else %}

                {% if entry.absent == True %}
                <td class="text-center border bg-danger"><span class="text-white">{{entry.date|date:"d"}}</span><hr><span class="text-white">{{entry.date|date:"D"}}</span></td>
                {% else %}
                <td class="text-center border"><span>{{entry.date|date:"d"}}</span><hr><span>{{entry.date|date:"D"}}</span></td>
                {% endif %}
                {% endif %}
                {% endfor %}
                
            </tr>

            </tbody>
            {% endfor %}
        </table>



    </div>
    
</div>


{% endblock content %}

myproject/templates/TodayEmpAttendanceList.html
{% extends 'base.html' %}

{% block content %}

<div class="card-box mb-30">
	
    <div class="pd-20 m-2">
        <h5>Employee_list</h5><hr>
       
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-info">

                <th>no</th>
                <th>Name</th>
                <th>Line</th>
                
                <th>Date</th>
                <th>Details</th>



            </tr>
            </thead>
            <tbody id="emplist">
            {% for p in emp %}
            <tr class="emptr">
                <td class="emppid">{{p.id}}</td>
                <td>
                    
                    {% if p.absent == True %}
                    <span class="text-danger">{{p.employee}}</span>
                    {% else %}
                    <span >{{p.employee}}</span>
                    {% endif %}

                </td>
                <td><b>{{p.employee.department}}</b></td>
                
                <td>{{p.date}}</td>
                <td>
                    {% if p.absent == True %}
                    <a href="#" class="text-danger h4" data-toggle="modal" data-target="#leave-{{p.id}}"><span class="badge badge-pill badge-danger">Absent</span></a>

                    
                    <div class="modal fade" id="leave-{{p.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-body text-center font-18">
                                    
                                    <h5 class="padding-top-30 mb-10 weight-500 text-danger">Choose Leave Type</h5>
                                    <h6 class="padding-top-20 mb-30 weight-500">{{p.employee}}</h6>
                                    <div class="padding-bottom-30 row" style="max-width: 400px; margin: 0 auto;">
                                        <div class="col-3">
                                            <a href="#" class="btn btn-md btn-warning">C</a>
                                        </div>

                                        <div class="col-3">
                                            <a href="#" class="btn btn-md btn-success">M</a>
                                        </div>

                                        <div class="col-3">
                                            <a href="#" class="btn btn-md btn-info">E</a>
                                        </div>

                                        <div class="col-3">
                                            <a href="#" class="btn btn-md btn-primary">M</a>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    

                    {% else %}
                    <a href="#" class="text-blue h4" data-toggle="modal" data-target="#confirmation-{{p.id}}"><span class="badge badge-pill badge-info">Attendance</span></a>

                    <div class="modal fade" id="confirmation-{{p.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-body text-center font-18">
                                    
                                    <h5 class="padding-top-30 mb-10 weight-500 text-danger">Are you sure to Absent?</h5>
                                    <h6 class="padding-top-20 mb-30 weight-500">{{p.employee}}</h6>
                                    <div class="padding-bottom-30 row" style="max-width: 170px; margin: 0 auto;">
                                        <div class="col-6">
                                            <button type="button" class="btn btn-secondary border-radius-100 btn-block confirmation-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                                            NO
                                        </div>
                                        <div class="col-6">
                                            <button type="button" class="btn btn-danger border-radius-100 btn-block confirmation-btn yesBtn" data-dismiss="modal"><i class="fa fa-check"></i></button>
                                            YES
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    {% endif %}

                   
                </td>
                
                
            </tr>
            {% endfor %}

            </tbody>
        </table>


    </div>
    
</div>
{% load static %}
<script src="{% static 'jquery/jquery-3.2.1.slim.min.js' %}"></script>

<script>
    $(document).ready(function() {
        //start comfirm absent
$("#emplist").on('click', '.yesBtn', function() {
    var currenttr = $(this).closest(".emptr");
    var empid = currenttr.find(".emppid").html();
    
    $.ajax({
    url: "/ComfirmAbsent/",
    method: "GET",
    data:{empid:empid},
    success: function(data){
        // console.log(data.status);

        alert('Successfully');
        window.setTimeout(function(){ } ,2000);
                        location.reload();

        // window.location.href = '/admin/';
        // window.open('https://www.codexworld.com', '_blank');
    },
    error:function(){
        alert('having some error contact to IT');
    },
                    
  });//end ajax



});//end comfirm absent
    }); // doucment ready function
</script>


{% endblock content %}

myproject/templates/departemt_list.html
{% extends 'base.html' %}

{% block content %}

<div class="card-box mb-30">
	
    <div class="pd-20 m-2">
        <h5>Department_list</h5><hr>
       
        <table class="table stripe hover nowrap">
            <thead>
            <tr class="table-info">

                <th class="text-center">Sir No</th>
                <th class="text-center">Department Name</th>
                
                <th class="text-center">Attendance</th>
                <th class="text-center">Today</th>
                <th>Report</th>



            </tr>
            </thead>
            <tbody id="deptmentlist">
            {% for p in dept %}
            <tr class="depttr">
                <td class="pid">{{p.id}}</td>
                <td class="table-plus text-center">
                    
                    <a href="{% url 'myapp:Employee_List_Filter_byLine' p.id %}" >{{p.department_name}}</a>
                </td>
                
                <td class="table-plus text-center"><button type="button" class="btn btn-sm btn-primary lineAttBtn">Attendance</button></td>
                <td class="table-plus text-center">
                    <a href="{% url 'myapp:TodayEmpAttendanceList' p.id %}" class="btn btn-sm btn-outline-info">Today</a>
                    <a href="{% url 'myapp:Employee_List_Filter_byLine' p.id %}" class="btn btn-sm btn-info">Employee</a>
                </td>
                <td><a href="{% url 'myapp:MonthlyAttendanceByLine' p.id %}" class="btn btn-sm btn-info">monthly report</a></td>
            </tr>
            {% endfor %}

            </tbody>
        </table>


    </div>
    
</div>
{% load static %}
<script src="{% static 'jquery/jquery-3.2.1.slim.min.js' %}"></script>

<script>
$(document).ready(function() {


//start line attendance
$("#deptmentlist").on('click', '.lineAttBtn', function() {
  var currenttr = $(this).closest(".depttr");
  var did = currenttr.find(".pid").html();
  $.ajax({
    url: "/DailyAttendanceByLine/",
    method: "GET",
    data:{did:did},
    success: function(data){
        // console.log(data.status);

        alert('Attendance Successfully');
        window.setTimeout(function(){ } ,2000);
                        location.reload();

        // window.location.href = '/admin/';
        // window.open('https://www.codexworld.com', '_blank');
    },
    error:function(){
        alert('having some error contact to IT');
    },
                    
  });//end ajax





});// end line attendance






}); //end document ready function
</script>



{% endblock content %}

myproject/templates/employee_att.html
{% extends 'base.html' %}

{% block content %}

<!-- time -->
<div class="row">
<div class="display-date">
  <span id="day">day</span>,
  <span id="daynum">00</span>
  <span id="month">month</span>
  <span id="year">0000</span>
  <span class="display-time"></span>
</div>
<!-- <div class="display-time"></div> -->
</div>

<!-- Bootstrap Select Start -->
<div class="row pd-20 card-box mb-30">
    <div class="col-md-4">
        
        <form action="{% url 'myapp:EmployeeAtt' %}" method="post">{% csrf_token %}
            <input type="number" name="emp" id="" autofocus class="form-control" placeholder="Please Scan">
            <input type="submit" hidden>
        </form>
        {% if message %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong> {{message}}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
        {% if success %}
        <hr>
        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
            <div class="card-header">CheckIn</div>
            <div class="card-body">
              <!-- <h5 class="card-title">EmployeeName :</h5> -->
              <p class="card-text">EmployeeID : {{emp_obj.id}}</p>
              <p class="card-text">EmployeeName : {{emp_obj.employee_name}}</p>
              <p class="card-text">Department : {{emp_obj.department}}</p>
            </div>
          </div>
        {% endif %}
        
        
          
         

    </div>
    <div class="col-md-8">
        <input type="text" name="" id="" placeholder="Attendance List of Today" class="form-control" disabled>
        <hr>
                
<div class="table-responsive">
	<table class="data-table table table-striped">
	  <thead>
	    <tr>
            <th class="text-center">Employee ID</th>
            <th>Employee</th>
            <th>CheckIn</th>
            <th>Checkout</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for p in emp %}
            <tr>
                <td class="table-plus text-center"><b>{{p.id}}</b></td>
                <td>{{p.employee}}</td>
                <td>{{p.entry_time}}</td>
                <td>{{p.checkout_time}}</td>
                

            </tr>
            {% endfor %}
	  </tbody>
	</table>
</div>
	

    </div>
</div>


<!-- Time Style and Script -->

<style>
  
  .display-date {
    text-align: center;
    margin-bottom: 10px;
    font-size: 1.6rem;
    font-weight: 600;
  }
  
  .display-time {
    display: flex;
    font-size: 2rem;
    font-weight: bold;
    /* border: 2px solid #ffd868; */
    padding: 10px 20px;
    border-radius: 5px;
    transition: ease-in-out 0.1s;
    transition-property: background, box-shadow, color;
    -webkit-box-reflect: below 2px
      linear-gradient(transparent, rgba(255, 255, 255, 0.05));
  }
  
  .display-time:hover {
    background: #ffd868;
    box-shadow: 0 0 30px#ffd868;
    color: #272727;
    cursor: pointer;
  }
  
  </style>
  
  
  <script>
    const displayTime = document.querySelector(".display-time");
  // Time
  function showTime() {
    let time = new Date();
    displayTime.innerText = time.toLocaleTimeString("en-US", { hour12: false });
    setTimeout(showTime, 1000);
  }
  
  showTime();
  
  // Date
  function updateDate() {
    let today = new Date();
  
    // return number
    let dayName = today.getDay(),
      dayNum = today.getDate(),
      month = today.getMonth(),
      year = today.getFullYear();
  
    const months = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ];
    const dayWeek = [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ];
    // value -> ID of the html element
    const IDCollection = ["day", "daynum", "month", "year"];
    // return value array with number as a index
    const val = [dayWeek[dayName], dayNum, months[month], year];
    for (let i = 0; i < IDCollection.length; i++) {
      document.getElementById(IDCollection[i]).firstChild.nodeValue = val[i];
    }
  }
  
  updateDate();
  </script>
  
  


{% endblock content %}

myproject/templates/getAbsent.html
{% extends 'base.html' %}

{% block content %}

<div class="card-box mb-2">

    

</div>



<div class="card-box mb-30">
	
    <div class="pd-20 m-1">
        
        <div class="row">

        <div class="">
        
        <button type="button" class="btn btn-sm m-2" data-bgcolor="#00b489" data-color="#ffffff" data-toggle="modal" data-target="#datefilter-modal">
             Filter <i class="fa fa-calendar" aria-hidden="true"></i>
        </button>
        <div class="modal fade" id="datefilter-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myLargeModalLabel">Filter</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <form action="{% url 'myapp:MonthlyAttendanceByLine' dept_obj.id %}" method="post">{% csrf_token %}
                    <div class="modal-body">
                        
                        <div class="row">
                            <div class="col-6">
                                <label for="startdate">Start Date</label>
                                <input type="date" name="startdate" id="" class="form-control">
                            </div>
                            <div class="col-6">
                                <label for="enddate">End Date</label>
                                <input type="date" name="enddate" id="" class="form-control">
                            </div>
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn" data-bgcolor="#00b489" data-color="#ffffff">Filter <i class="fa fa-calendar" aria-hidden="true"></i></button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="">
        <form action="{% url 'myapp:getAbsent' dept_id %}" method="get">{% csrf_token %}
            <input type="date" name="startdate" value="{{startdate}}" hidden>
            <input type="date" name="enddate" value="{{enddate}}" hidden>
            <input type="number" name="lid" value="{{dept_id}}" hidden>
            <input type="submit" value="Absent" class="btn btn-sm btn-danger m-2">
        </form>
    </div>
</div>


        <hr>
       
        <table class="table table-responsive">
            <a href="#" class="h4"> [ {{dept_obj}} ] </a>
            {% for employee in emp %}
            <tbody>
            
            <tr>
                <td>{{employee.employee_name}}</td>
                
                {% for entry in employee.daily_attendance_report_set.all %}
                
                {% if entry.created_at < fd or entry.created_at > ed %}
                    <!-- <td>-</td> -->
                {% else %}
                    
                {% if entry.absent == True %}
                <td class="text-center border">
                    {% if entry.weekno == 5 %}
                    <span class="text-blue h5">{{entry.date|date:"d"}}</span><hr>
                    <span class="text-blue h5">{{entry.date|date:"D"}}</span>
                    {% else %}
                    <span class="text-danger h5">{{entry.date|date:"d"}}</span><hr>
                    <span class="text-danger h5">{{entry.date|date:"D"}}</span>
                    {% endif %}
                    
                </td>
                {% else %}
                
                {% endif %}



                {% endif %}
                
                   
              

                {% endfor %}
                
            </tr>

            </tbody>
            {% endfor %}
        </table>


    </div>
    
</div>


{% endblock content %}